# Generated by Django 3.0.7 on 2020-06-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title of your page.', max_length=20, unique=True)),
                ('slug', models.CharField(blank=True, editable=False, help_text="Unique URL path to access this page's page. Generated by the system.", max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this page was created. Automatically generated when the model saves.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time this page was updated. Automatically generated when the model updates.')),
                ('content', models.TextField(default='Write the content of your page here.')),
                ('sources', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
